VLT-1186 adding new bank requests
checkout/checkout-api-reference pull request #217
Opened 2020-11-30 11:43 UTC by neil-rastogi-cko

This is adding the relevant new bank requests for patch and delete endpoint, there are one or two things that need clarifying but the majority of it is there, based on the spec below:

https://checkout.atlassian.net/wiki/spaces/VLT/pages/1777041711/Phase+3+4+-+expanding+instrument+management+in+Vault#Returning-bank-account-enrichment

2020-11-30 11:52 UTC, anthony-simpson-cko commented on spec/components/schemas/Instruments/UpdateBankInstrumentRequest.yaml
> +  account_type:
`Type` cannot be changed, so shouldn't be in the request

2020-11-30 11:58 UTC, anthony-simpson-cko commented on spec/paths/instruments.yaml
> +    Deletes a bank account payment instrument.
My understanding is that this endpoint will be able to delete card instruments as well as bank account instruments

2020-11-30 12:01 UTC, anthony-simpson-cko commented on spec/paths/instruments.yaml
> +  summary: Deletes an instrument
To be consistent with other labels I think it should be
`Delete an instrument`
rather than
`Deletes an instrument`

2020-11-30 12:15 UTC, neil-rastogi-cko commented on spec/paths/instruments.yaml
> +    Deletes a bank account payment instrument.
a question to check with Ramani

2020-12-01 09:41 UTC, anthony-simpson-cko commented on spec/paths/instruments.yaml
> +  summary: Deletes an instrument
This isn't resolved

2020-12-01 09:41 UTC, anthony-simpson-cko commented on spec/paths/instruments.yaml
> +    Deletes a bank account payment instrument.
This isn't resolved

2020-12-01 09:43 UTC, anthony-simpson-cko commented on spec/paths/instruments.yaml
> +    Delete an bank account payment instrument.
Rich agrees that it should also delete card instruments as well as bank account instruments
https://checkout.atlassian.net/wiki/spaces/VLT/pages/1857094333/Instrument+Management+Acceptance+Criteria

2020-12-01 10:46 UTC, neil-rastogi-cko commented on spec/paths/instruments.yaml
> +    Delete an bank account payment instrument.
as per our slack conversation changed the text to make it a generic delete endpoint and renamed it rather than using dropdown option.

2020-12-01 10:46 UTC, neil-rastogi-cko commented on spec/paths/instruments.yaml
> +    Deletes a bank account payment instrument.
done

2020-12-01 11:29 UTC, rich-cooper-cko requested changes
A couple comments, the majority looks good though 👍

2020-12-01 11:29 UTC, rich-cooper-cko commented on spec/paths/instruments.yaml
> +           $ref: '#/components/schemas/ValidationError'
Do we need a 404 instrument not found?

2020-12-01 11:29 UTC, rich-cooper-cko commented on spec/components/schemas/UpdateBankCustomerRequest.yaml
> +    description: Determines if this customer is set as the default for the instrument
This should be flipped I think `Determines if this instrument is set as the default for the customer`

2020-12-01 11:29 UTC, rich-cooper-cko commented on spec/paths/instruments.yaml
> +    # - ApiKey: []
Will this also support secret key authentication?

2020-12-01 11:29 UTC, rich-cooper-cko commented on spec/paths/instruments.yaml
> +    # - ApiKey: []
Will this also support secret key authentication?

2020-12-01 11:29 UTC, rich-cooper-cko commented on spec/paths/instruments.yaml
> +      description: Internal Error
Do we need a 404 instrument not found?

2020-12-01 11:29 UTC, rich-cooper-cko commented on spec/paths/instruments.yaml
> +  summary: Update an instrument
This doesn't seem to have the instrument identifier anywhere? Should it be a path parameter?

2020-12-01 15:55 UTC, neil-rastogi-cko commented on spec/paths/instruments.yaml
> +           $ref: '#/components/schemas/ValidationError'
yes we do, it is possible to type a valid instrumentId syntactically but won't when it comes to actually deleting the instrument it can't be deleted since it doesn't exist. It is also on the account  key configuration api for delete endpoint

2020-12-01 16:00 UTC, neil-rastogi-cko commented on spec/paths/instruments.yaml
> +      description: Internal Error
I believe so looking at all the other specs they have it too, it is possible to enter a valid instrumentId but not one that is present.

2020-12-01 16:01 UTC, rich-cooper-cko commented on spec/paths/instruments.yaml
> +           $ref: '#/components/schemas/ValidationError'
Sorry I meant that 404 is missing from the spec, my bad

2020-12-01 16:02 UTC, rich-cooper-cko commented on spec/paths/instruments.yaml
> +      description: Internal Error
Sorry I meant that 404 is missing from the spec

2020-12-01 16:09 UTC, neil-rastogi-cko commented on spec/paths/instruments.yaml
> +  summary: Update an instrument
added cheers

2020-12-01 16:10 UTC, neil-rastogi-cko commented on spec/components/schemas/UpdateBankCustomerRequest.yaml
> +    description: Determines if this customer is set as the default for the instrument
not really sure to be honest, if you think this sounds better I will change it.

2020-12-01 16:19 UTC, anthony-simpson-cko commented on spec/components/schemas/Instruments/DeleteInstrumentRequest.yaml
> +  - instrumentId
Everything else in the docs is formatted in snake_case including id fields, so should be `instrument_id`

2020-12-01 16:27 UTC, anthony-simpson-cko requested changes

2020-12-01 16:27 UTC, anthony-simpson-cko commented on spec/components/schemas/Instruments/DeleteInstrumentRequest.yaml
> +  - instrumentId
Also, this is wrong

Look at https://checkout.atlassian.net/wiki/spaces/VLT/pages/1777041711/Phase+3+4+-+expanding+instrument+management+in+Vault#Deleting-instruments

The `src_` should be passed in the query string, not the request body
```DELETE: https://api.checkout.com/instruments/src_4gzeau5o2uqubbk6fufs3m7p54```

2020-12-01 16:32 UTC, neil-rastogi-cko commented on spec/components/schemas/Instruments/DeleteInstrumentRequest.yaml
> +  - instrumentId
done

2020-12-01 16:44 UTC, neil-rastogi-cko commented on spec/components/schemas/Instruments/DeleteInstrumentRequest.yaml
> +  - instrumentId
Yep I know it should be but I thought that how it was done in this open api spec but actually I can see how you can do it now.

2020-12-01 16:56 UTC, anthony-simpson-cko commented
This should be `/instruments/{id}`

![Screenshot 2020-12-01 at 16 55 24](https://user-images.githubusercontent.com/64790034/100771177-042d9680-33f6-11eb-9adb-bea53ba3be36.png)

2020-12-01 16:58 UTC, anthony-simpson-cko commented
![Screenshot 2020-12-01 at 16 57 47](https://user-images.githubusercontent.com/64790034/100771446-5969a800-33f6-11eb-9b0d-e9390c1a6e1e.png)

So should this

2020-12-01 17:19 UTC, anthony-simpson-cko commented
I think the explanation of the `default` field on the `customer` object is more accurate and informative on the master branch ie.

> If true, sets this instrument as the default for the customer (if false, no changes are actioned)

rather than 

> Determines if this instrument is set as the default for the customer

2020-12-01 17:52 UTC, rich-cooper-cko approved these changes

2020-12-01 18:02 UTC, anthony-simpson-cko approved these changes

2020-12-21 08:12 UTC, anthony-roe-cko approved these changes

2021-01-13 13:24 UTC, merged