DOC 394: Introduce reflow endpoints documentation
checkout/checkout-api-reference pull request #285
Opened 2021-05-12 14:51 UTC by roberto-brancorhodes-cko

### Jira link
 
-  [NTS-394](https://checkout.atlassian.net/browse/DOC-394)
 
### Functional comments
- Introduce api specs for reflow endpoints to public api documentation.
 
For the following endpoints:

**-Reflow by event id: POST workflows/events/{eventId}/reflow**

-Will allow the merchants to reflow a past event by event id. ALL workflows that match the event conditions for event type and entity id will be triggered.

**-Reflow by event and workflow id: POST workflows/events/{eventId}/workflow/{workflowid}/reflow**

-Will allow the merchants to reflow a past event by event id and a specific workflow id. If the workflow id provided is valid, exists and matches the event and entity conditions then the workflow actions for the specific workflow will be triggered.

**-Reflow by subject id :  POST workflows/events/subject/{subjectId}/reflow**

-Will allow the merchants to reflow a past events by subject id. ALL workflows that match the event conditions for events associated with the subject (event type and entity id) will be triggered.

**-Reflow by subject id and workflow id:  POST workflows/events/subject/{subjectId}/workflow/{workflowid}/reflow**

-Will allow the merchants to reflow a past events by subject id and a specific workflow id. If the workflow id provided is valid, exists and matches the event and entity conditions for the events associated with the subject id then the workflow actions for the specific workflow will be triggered.

**-Reflow by ids: POST /workflows/events/reflow** 

-Reflows multiple event ids or subject ids and optional workflowIds

-Will allow the merchants to reflow a past events attached to multiple subject ids and multiple workflow ids OR by multiple event ids and multiple workflows ids. The subject ids and event ids are mutually exclusive you can either provide events or subjects but not both. workflow Ids are optional in both scenarios. If no workflow ids are provided, ALL workflows that match the event conditions for event type and entity id will be triggered.

 
### Other comments and links
-
 
[Code Review Guidelines](https://checkout.atlassian.net/wiki/spaces/CoreEng/pages/657064052/Code+Reviews)

2021-05-13 10:25 UTC, toby-knott-cko commented on spec/paths/flow/reflows/events@{eventId}@reflow.yaml
> +      description: QA
@roberto-brancorhodes-cko Should I change these (and the others) to the live and sandbox API URLs? – so https://api.checkout.com/workflows/events/{eventId}/reflow and https://api.sandbox.checkout.com/workflows/events/{eventId}/reflow in this case?

Also, are reflows a subset of the workflows endpoints? If so, should they be included under the workflows section in the API reference, rather than being their own section? I think having them separately should be fine, but we'd have to manually specify the URLs here, because the endpoints usually take https://api.checkout.com as the base and then tack on the path of the endpoint (which in this case would miss out the `/workflows` bit). Hope that makes sense.

2021-05-13 11:57 UTC, konstantinos-kafkas-cko requested changes

2021-05-13 11:57 UTC, konstantinos-kafkas-cko commented on spec/paths/flow/reflows/events@{eventId}@reflow.yaml
> +      description: QA
This is a good observation all the links should change from qa to sbox & prod. Check other examples within the repo

2021-05-13 11:57 UTC, konstantinos-kafkas-cko commented on spec/paths/flow/reflows/events@{eventId}@workflow@{workflowId}@reflow.yaml
> +      description: QA
URLs should point to sbox and prod

2021-05-13 12:31 UTC, toby-knott-cko commented on spec/components/schemas/Flow/reflow/reflow-events-by-subject-and-workflow-ids.yaml
> +    description: A list of string subject Ids
@roberto-brancorhodes-cko Am I right in thinking that subject IDs can be things like payment IDs (`pay_`), dispute IDs (`dsp_`), etc?

2021-05-13 12:51 UTC, toby-knott-cko commented on spec/paths/flow/reflows/events@subject@{subjectId}@reflow.yaml
> +        pattern: ^sbj_[a-z0-9]{26}$
@roberto-brancorhodes-cko What exactly does the subject ID refer to? In the /event/reflow endpoint, we have payment IDs as examples in the subjects array – is that correct?

2021-05-13 13:59 UTC, roberto-brancorhodes-cko commented on spec/components/schemas/Flow/reflow/reflow-events-by-subject-and-workflow-ids.yaml
> +    description: A list of string subject Ids
Yes that is correct 👍

2021-05-13 14:01 UTC, roberto-brancorhodes-cko commented on spec/paths/flow/reflows/events@subject@{subjectId}@reflow.yaml
> +        pattern: ^sbj_[a-z0-9]{26}$
yes that is correct, I think I need to change this though. the spec shows a fixed pattern thats not accurate to all possibilities

2021-05-17 13:18 UTC, toby-knott-cko approved these changes

2021-05-18 13:03 UTC, konstantinos-kafkas-cko approved these changes

2021-05-18 13:17 UTC, merged