Update Node Samples
checkout/checkout-api-reference pull request #340
Opened 2021-06-23 15:26 UTC by ioan-ghisoi-cko

2021-06-23 15:30 UTC, jack-hutchinson-cko requested changes

2021-06-23 15:30 UTC, jack-hutchinson-cko commented on abc_spec/code_samples/Node/customers@{id}/get.js
> +import { Checkout } from 'checkout-node-sdk';
Can you add empty lines to match the other files for consistency?

2021-06-23 15:50 UTC, ioan-ghisoi-cko commented on abc_spec/code_samples/Node/customers@{id}/get.js
> +import { Checkout } from 'checkout-node-sdk';
done

2021-06-24 07:49 UTC, jack-hutchinson-cko approved these changes

2021-07-02 11:35 UTC, merged