VLT-1914: add apple pay for nas specs
checkout/checkout-api-reference pull request #359
Opened 2021-07-13 08:55 UTC by rich-cooper-cko

2021-07-13 09:15 UTC, ashley-barrett-cko requested changes

2021-07-13 09:15 UTC, ashley-barrett-cko commented on nas_spec/components/schemas/ApplePay/ApplePaySigningRequestResponse.yaml
> +    example: -----BEGIN CERTIFICATE-----MIIBSDCB8AIBADCBjzELMAkGA1UEBhMCR0IxDzANBgNVBAgMBkxvbmRvbjEPMA0GA1UEBwwGTG9uZG9uMRUwEwYDVQQKDAxDaGVja291dC5jb20xCzAJBgNVBA8MAklUMRUwEwYDVQQDDAxjaGVja291dC5jb20
BEGIN NEW CERTIFICATE REQUEST

2021-07-13 09:15 UTC, ashley-barrett-cko commented on nas_spec/components/schemas/ApplePay/ApplePaySigningRequestResponse.yaml
> +    example: -----BEGIN CERTIFICATE-----MIIBSDCB8AIBADCBjzELMAkGA1UEBhMCR0IxDzANBgNVBAgMBkxvbmRvbjEPMA0GA1UEBwwGTG9uZG9uMRUwEwYDVQQKDAxDaGVja291dC5jb20xCzAJBgNVBA8MAklUMRUwEwYDVQQDDAxjaGVja291dC5jb20
END NEW CERTIFICATE REQUEST

2021-07-13 09:28 UTC, rich-cooper-cko commented on nas_spec/components/schemas/ApplePay/ApplePaySigningRequestResponse.yaml
> +    example: -----BEGIN CERTIFICATE-----MIIBSDCB8AIBADCBjzELMAkGA1UEBhMCR0IxDzANBgNVBAgMBkxvbmRvbjEPMA0GA1UEBwwGTG9uZG9uMRUwEwYDVQQKDAxDaGVja291dC5jb20xCzAJBgNVBA8MAklUMRUwEwYDVQQDDAxjaGVja291dC5jb20
I checked the api and it came back as `BEGIN CERTIFICATE REQUEST`. Updated accordingly

2021-07-14 11:42 UTC, toby-knott-cko requested changes

2021-07-14 11:42 UTC, toby-knott-cko commented on nas_spec/swagger.yaml
> +    description: Manage your apple pay certificates in order to process via apple pay
```suggestion
    description: Manage your Apple Pay certificates in order to process payments via Apple Pay.  
```

2021-07-14 11:42 UTC, toby-knott-cko commented on nas_spec/swagger.yaml
> +      - Apple Pay
I think it makes sense to have these Apple Pay endpoints part of the 'Handle payments and payouts section' (underneath Forex). What do you think?

2021-07-15 08:00 UTC, rich-cooper-cko commented on nas_spec/swagger.yaml
> +      - Apple Pay
Sure I can move these

2021-07-15 09:21 UTC, toby-knott-cko submitted a review, later dismissed

2021-07-19 10:41 UTC, anthony-simpson-cko submitted a review, later dismissed

2021-08-06 10:54 UTC, ashley-barrett-cko approved these changes

2021-08-06 11:19 UTC, toby-knott-cko approved these changes

2021-08-06 11:31 UTC, merged