Add 3DS challenge_indicator field
checkout/checkout-api-reference pull request #441
Opened 2021-11-03 09:16 UTC by cristina-szilagyi-cko

New `3ds.challenge_indicator` field added on https://api-reference.checkout.com/#operation/requestAPaymentOrPayout.

2021-11-03 09:24 UTC, ben-ahmady-cko commented on abc_spec/components/schemas/Payments/3dsRequest.yaml
> +      - no_preference (default) – You have no preference whether or not a challenge should be performed.
So we can actually do this instead of having "`(default)`" in the line of one of the strings:

```
enum:
   - ThingA
   - ThingB
   - ThingC
default: ThingA

2021-11-11 08:12 UTC, chrisi-webster-cko requested changes
With the enums, we just want the option that the user can provide in the API. If you need to provide a description, you can create a list in the description field. 

This is what yours looks like at the moment
<img width="808" alt="Screenshot 2021-11-11 at 08 06 39" src="https://user-images.githubusercontent.com/77628673/141261353-582b174c-6583-4b47-b1f8-6dab170f5379.png">

But here's an example of a list in a description that you could do. 
<img width="576" alt="Screenshot 2021-11-11 at 08 10 00" src="https://user-images.githubusercontent.com/77628673/141261668-9d4559f0-aa6d-4a38-92fe-bb9ff86b3a5e.png">

Then keep the enum values so it's just:
```
enum: 
   - no_preference
   - no_challenge_requested
   - challenge_request_by_merchant
   - challenge_request_as_mandate
default: no_preference
```

2021-11-11 16:27 UTC, Joshua-Bedeau-cko commented on abc_spec/components/schemas/Payments/3dsRequest.yaml
> +      - challenge_request_by_merchant – You want a challenge to be performed.
challenge_request_by_merchant should be replaced with challenge_requested

2021-11-11 16:27 UTC, Joshua-Bedeau-cko requested changes

2021-11-11 16:27 UTC, Joshua-Bedeau-cko commented on abc_spec/components/schemas/Payments/3dsRequest.yaml
> +      - challenge_request_as_mandate – Local requirements demand a challenge be performed.
challenge_request_as_mandate  should be replaced with challenge_requested_mandate

2021-11-11 17:56 UTC, Joshua-Bedeau-cko approved these changes

2021-11-11 17:57 UTC, ben-ahmady-cko commented
@cristina-szilagyi-cko @chrisi-webster-cko I discussed this one with Josh so going ahead and merging, sorry it's a bit messy

2021-11-11 17:57 UTC, merged