GET dispute scheme files endpoint
checkout/checkout-api-reference pull request #525
Opened 2022-03-07 12:43 UTC by konstantinos-kafkas-cko

# Description of changes in PR

Introduces the specs for the newly introduced dispute scheme file endpoint to both MBC and NAS websites. This PR won't be merged until the BETA testing is passing  which means the selected merchants tested it and approved it

GET dispute scheme files endpoint: `https://api.checkout.com/disputes/dsp_rbhwd2qrg13uhrp2newf/schemefiles`

## Checklist

- [ ] Added a changelog entry on the `swagger.yaml` file
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-10-28 09:30 UTC, konstantinos-mastropavlos-cko approved these changes
This is now RELEASED in PRODUCTION - Let's update the docs! ⭐

2022-11-01 16:50 UTC, sebastian-garcia-cardona-cko requested changes

2022-11-01 16:50 UTC, sebastian-garcia-cardona-cko commented on abc_spec/paths/disputes@{dispute_id}@schemefiles.yaml
> +  summary: Get dispute scheme files (BETA)
```suggestion
  summary: Get dispute scheme files
```

2022-11-01 16:50 UTC, sebastian-garcia-cardona-cko commented on abc_spec/paths/disputes@{dispute_id}@schemefiles.yaml
> +  description: Returns all the scheme files of a dispute using the dispute identifier.
```suggestion
  description: |
    <span style="font-size: 14px; font-weight: 500; color: rgb(60, 4, 133); background-color: rgb(237, 222, 255); border-radius: 4px; padding: 2px 6px" >Beta</span><p></p>
    Returns all of the scheme files of a dispute using the dispute identifier.
```

2022-11-01 16:50 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/disputes@{dispute_id}@schemefiles.yaml
> +  summary: Get dispute scheme files (BETA)
```suggestion
  summary: Get dispute scheme files
```

2022-11-01 16:50 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/disputes@{dispute_id}@schemefiles.yaml
> +  description: Returns all the scheme files of a dispute using the dispute identifier.
```suggestion
  description: |
    <span style="font-size: 14px; font-weight: 500; color: rgb(60, 4, 133); background-color: rgb(237, 222, 255); border-radius: 4px; padding: 2px 6px" >Beta</span><p></p>
    Returns all of the scheme files of a dispute using the dispute identifier.
```

2022-11-01 16:50 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/disputes@{dispute_id}@schemefiles.yaml
> +  description: Returns all the scheme files of a dispute using the dispute identifier.
```suggestion
  description: |
    <span style="font-size: 14px; font-weight: 500; color: rgb(60, 4, 133); background-color: rgb(237, 222, 255); border-radius: 4px; padding: 2px 6px" >Beta</span><p></p>
    Returns all of the scheme files of a dispute using the dispute identifier.
```

2022-11-03 12:02 UTC, sebastian-garcia-cardona-cko submitted a review, later dismissed

2022-11-14 21:10 UTC, konstantinos-mastropavlos-cko commented
@sebastian-garcia-cardona-cko reverted previously committed BETA, as the feature is perceived as final - let me know if any thoughts 🙏🏼

2022-11-14 21:10 UTC, konstantinos-mastropavlos-cko approved these changes

2022-11-15 10:13 UTC, sebastian-garcia-cardona-cko approved these changes

2022-11-15 10:31 UTC, sebastian-garcia-cardona-cko approved these changes

2022-11-15 10:32 UTC, merged