Replaces all instances of format ISO 8601 with datetime
checkout/checkout-api-reference pull request #547
Opened 2022-04-01 16:02 UTC by ben-ahmady-cko

# Description of changes in PR

The format `ISO-8601` doesn't exist in OAS; it should be `datetime`

Don't think this should be in changelog but happy to discuss

2022-04-01 16:07 UTC, jay-glass-cko requested changes

2022-04-01 16:07 UTC, jay-glass-cko commented on abc_spec/components/schemas/Disputes/Dispute.yaml
> +    format: datetime
According to the [spec](https://swagger.io/docs/specification/data-models/data-types/#string) the correct format has a hyphen: `date-time`

2022-04-01 16:10 UTC, ben-ahmady-cko commented on abc_spec/components/schemas/Disputes/Dispute.yaml
> +    format: datetime
Yeah just seen that, I'm surprised the build succeeded locally 🤔 

Thanks! Will push up a fix

2022-04-01 16:11 UTC, jay-glass-cko commented on abc_spec/components/schemas/Disputes/Dispute.yaml
> +    format: datetime
I strongly recommend adding open api spec validation part of the automated PR checks. Would catch this kind of thing early on and give us an extra level of confidence in the spec. Let me know if you'd like any more info/help.

2022-04-01 16:17 UTC, ben-ahmady-cko commented on abc_spec/components/schemas/Disputes/Dispute.yaml
> +    format: datetime
Fix pushed up @jay-glass-cko, seems to be building OK now

2022-04-01 16:22 UTC, ben-ahmady-cko commented on abc_spec/components/schemas/Disputes/Dispute.yaml
> +    format: datetime
Sorry, I commented before I'd refreshed. 

I completely agree about adding validation: we're in the process of revamping the whole API reference and validations will be implemented when that project is completed, but it's managed by the Web team at the moment. For the moment ideally I'd like to just fix this particular identified issue.

2022-04-04 10:36 UTC, jack-hutchinson-cko approved these changes

2022-04-04 10:37 UTC, ben-ahmady-cko commented on abc_spec/components/schemas/Disputes/Dispute.yaml
> +    format: datetime
I'll resolve this thread so we can get this merged but feel free to reach out to me on Slack if you'd like more context about API reference business/process improvements @jay-glass-cko

2022-04-04 10:37 UTC, merged