Updated Processing bag for PayPal
checkout/checkout-api-reference pull request #581
Opened 2022-05-20 05:49 UTC by yelena-pakumirzakova-cko

Jira ticket - https://checkout.atlassian.net/jira/software/c/projects/APM/boards/768?modal=detail&selectedIssue=APM-4670

- Added payload for PayPal v2(Nas)

2022-06-02 12:06 UTC, guven-kurt-cko approved these changes

2022-06-06 10:17 UTC, sebastian-garcia-cardona-cko requested changes

2022-06-06 10:17 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingSettings.yaml
> +    description: Invoice id number
```suggestion
    description: Invoice ID number
```

2022-06-06 10:17 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingSettings.yaml
> +              description: Ticket number/id as issued by the airline.
```suggestion
              description: Ticket number/ID as issued by the airline.
```

2022-06-14 11:02 UTC, guven-kurt-cko submitted a review, later dismissed

2022-06-15 13:17 UTC, merged