[GTW-6943] Add new pagination GET Payments endpoint
checkout/checkout-api-reference pull request #586
Opened 2022-05-30 12:07 UTC by sam-bonheure-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs (will be handled by @jason-dantzer

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-09-14 17:17 UTC, jason-dantzer-cko commented on abc_spec/paths/payments.yaml
> +  summary: Get payments
1. The endpoint should be named Get payment lists. 
2. Can we add a beta tag next to the endpoint title?

2022-09-29 09:00 UTC, katy-hughes-cko commented on abc_spec/paths/payments.yaml
> +  operationId: getPayments
is this just an arbitrary id ? should this be called getPaymentLists too?

2022-09-29 09:04 UTC, jason-dantzer-cko approved these changes

2022-09-29 09:11 UTC, david-chandler-cko commented on abc_spec/components/schemas/Payments/PaymentPaged.yaml
> +    description: The total number of payments retrieved (without taking into consideration skip and limit parameters)
I think this is ambiguous... do we mean "The total number of **matching** payments _available_"?
Right now 'retrieved' looks like it means the number returned by the paged request.

2022-09-29 09:11 UTC, david-chandler-cko commented on abc_spec/paths/payments.yaml
> +      description: A reference (such as an order ID) that you can use later to identify the payment.
```suggestion
      description: A reference (such as an order ID) that you can use later to identify the payment
```

2022-09-29 09:11 UTC, david-chandler-cko commented on nas_spec/paths/payments.yaml
> +    Returns a list of all payments for your business. The results will be
```suggestion
    Returns a list of all matching payments for your business. The results will be
```

2022-09-29 09:11 UTC, david-chandler-cko commented on nas_spec/components/schemas/Payments/PaymentPaged.yaml
> +    description: The total number of payments retrieved (without taking into consideration skip and limit parameters)
```suggestion
    description: The total number of matching payments available (without taking into consideration skip and limit parameters)
```

2022-09-29 09:11 UTC, david-chandler-cko commented on abc_spec/paths/payments.yaml
> +    Returns a list of all payments for your business. The results will be returned in reverse chronological order,
```suggestion
    Returns a list of all matching payments for your business. The results will be returned in reverse chronological order,
```

2022-09-29 10:22 UTC, katy-hughes-cko commented on abc_spec/paths/payments.yaml
> +  operationId: getPayments
@sam-bonheure-cko

2022-09-30 09:03 UTC, jason-dantzer-cko commented on abc_spec/paths/payments.yaml
> +  operationId: getPayments
I don't know what that is, Sam might be better to answer this one

2022-09-30 09:05 UTC, jason-dantzer-cko commented on abc_spec/components/schemas/Payments/PaymentPaged.yaml
> +    description: The total number of payments retrieved (without taking into consideration skip and limit parameters)
you are right, it is indeed "The total number of matching payments available" not the total ones returned

2022-09-30 09:09 UTC, sam-bonheure-cko commented on abc_spec/paths/payments.yaml
> +  operationId: getPayments
Not sure either, don't think this is visualized in the UI anywhere

2022-09-30 09:10 UTC, jason-dantzer-cko requested changes

2022-09-30 09:10 UTC, jason-dantzer-cko commented on abc_spec/components/schemas/Payments/PaymentPaged.yaml
> +    description: The total number of payments retrieved (without taking into consideration skip and limit parameters)
Change this to match NAS "The total number of matching payments available (without taking into consideration skip and limit parameters)"

2022-09-30 10:40 UTC, jason-dantzer-cko approved these changes

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko requested changes

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on abc_spec/paths/payments.yaml
> +    Returns a list of all matching payments for your business. The results will be returned in reverse chronological order,
```suggestion
    Returns a list of your business' payments that match the specified reference. Results are returned in reverse chronological order, with the most recent payments shown first.
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on abc_spec/paths/payments.yaml
> +    showing the last made payment first.
```suggestion
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on abc_spec/paths/payments.yaml
> +      description: The numbers of results to return
```suggestion
      description: The numbers of results to retrieve
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on abc_spec/paths/payments.yaml
> +      description: A reference (such as an order ID) that you can use later to identify the payment
```suggestion
      description: A reference, such as an order ID, that can be used to identify the payment
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/PaymentPaged.yaml
> +    description: The numbers of items to return
```suggestion
    description: The numbers of results to retrieve
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/PaymentPaged.yaml
> +    description: The total number of matching payments available (without taking into consideration skip and limit parameters)
```suggestion
    description: The total number of results matching the payment reference. This number is unaffected by the values of the `skip` and `limit` parameters
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/payments.yaml
> +    Returns a list of all matching payments for your business. The results will be
```suggestion
    Returns a list of your business' payments that match the specified reference. Results are returned in reverse chronological order, with the most recent payments shown first.
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/payments.yaml
> +    returned in reverse chronological order, showing the last made payments first. You
```suggestion
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/payments.yaml
> +    can use the optional parameters below to skip or limit results.
```suggestion
    You can use the optional parameters below to skip or limit results.
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/payments.yaml
> +      description: The numbers of results to return
```suggestion
      description: The numbers of results to retrieve
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/payments.yaml
> +      description: A reference (such as an order ID) that you can use later to identify the payment.
```suggestion
      description: A reference, such as an order ID, that can be used to identify the payment
```

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/payments.yaml
> +      description: A reference (such as an order ID) that you can use later to identify the payment.
I've modified the copy based on the previous wording, but is the reference here not the query parameter that's being used to retrieve the results?

If so, I can update the description.

2022-09-30 16:56 UTC, sebastian-garcia-cardona-cko commented on abc_spec/paths/payments.yaml
> +      description: A reference (such as an order ID) that you can use later to identify the payment
I've modified the copy based on the previous wording, but is the reference here not the query parameter that's being used to retrieve the results?

If so, I can update the description.

2022-09-30 17:27 UTC, sam-bonheure-cko commented on abc_spec/components/schemas/Payments/PaymentPaged.yaml
> +    description: The numbers of items to return
Good point this is limited to 100 for now in public beta. With a default of 10.

2022-09-30 18:45 UTC, jason-dantzer-cko commented on nas_spec/paths/payments.yaml
> +      description: A reference (such as an order ID) that you can use later to identify the payment.
Currently only reference is used so we can have the description stating reference. If we add other query parameters later we would need to update this endpoints description

2022-10-03 08:22 UTC, jason-dantzer-cko approved these changes

2022-10-03 08:33 UTC, sam-bonheure-cko commented on abc_spec/components/schemas/Payments/PaymentPaged.yaml
> +
whitespace

2022-10-03 14:58 UTC, sebastian-garcia-cardona-cko approved these changes

2022-10-03 15:04 UTC, merged