Update fawry nas source request and response specs
checkout/checkout-api-reference pull request #604
Opened 2022-06-21 17:26 UTC by guven-kurt-cko

[Ticket](https://checkout.atlassian.net/browse/APM-3662)
- Update source > request and response objects for fawry

2022-06-22 07:06 UTC, ben-ahmady-cko commented
Thanks, the GW team needs to review UPAPI PRs so I've forwarded to @Joshua-Bedeau-cko and Enrica Mameli to take a look at

2022-06-23 08:57 UTC, ahmed-farghaly-cko approved these changes

2022-07-04 17:57 UTC, Joshua-Bedeau-cko requested changes

2022-07-04 17:57 UTC, Joshua-Bedeau-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestFawrySource.yaml
> +        description: "The customer's email address."
This is PII - We cannot release this until we have appropriate masking. 
https://checkout.atlassian.net/browse/GTW-7614

2022-07-08 12:53 UTC, saad-khan-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestFawrySource.yaml
> +        description: "The customer's email address."
@Joshua-Bedeau-cko I think this PR can be merged now as the task you mentioned was released to production

2022-07-08 12:54 UTC, saad-khan-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestFawrySource.yaml
> +        description: "The customer's email address."
@Joshua-Bedeau-cko can you please approve the PR now ? As the comment was marked with the `request changes` state, I can't merge until you approve it

2022-07-11 08:29 UTC, merged