[APM-4112] Add Benefit PG Source
checkout/checkout-api-reference pull request #618
Opened 2022-06-30 14:59 UTC by andrew-berestov-cko

# Description of changes in PR

[//]: Added Benefit PG Source

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-06-30 15:03 UTC, alex-larin-cko approved these changes

2022-07-04 08:37 UTC, andrew-berestov-cko commented
@adam-young-cko Could you kindly approve this PR?

2022-07-04 09:23 UTC, sebastian-garcia-cardona-cko approved these changes

2022-07-04 09:34 UTC, sebastian-garcia-cardona-cko commented
Please confirm updates with @Joshua-Bedeau-cko or Enrica Mameli before merging.

2022-07-04 17:52 UTC, Joshua-Bedeau-cko requested changes

2022-07-04 17:52 UTC, Joshua-Bedeau-cko commented on nas_spec/changelog.md
> +| 2022/06/30 | Add Bebefit PG Request and Response sources                                                                                         |
Spelling mistake

2022-07-04 17:52 UTC, Joshua-Bedeau-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseBenefitSource.yaml
> +        description: 'The Benefit error code for transaction processing.'
Have we agreed to put this in the source response? Even if we are not reusing the GW error code for this (which is another debate) an error code feels very much like processing to me and could change with each transaction for a given source. Can this please be flagged with APP Product.

2022-07-05 10:33 UTC, andrew-berestov-cko commented on nas_spec/changelog.md
> +| 2022/06/30 | Add Bebefit PG Request and Response sources                                                                                         |
Thanks for noticing, Joshua. I have fixed that

2022-07-05 10:34 UTC, andrew-berestov-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseBenefitSource.yaml
> +        description: 'The Benefit error code for transaction processing.'
That one seems generic to all APMs. I think we can remove that. Will have a talk to anastasiya.piatrkouskaya

2022-08-03 09:23 UTC, tania-asimionesei-cko commented
Please note that on the 27th of July we had a BREAKING CHANGE release, where the ABC and NAS versions of the API reference were switched in line with company-wide NAS readiness OKR and initiative. Therefore please make sure that you address any conflicts and updates in line with the latest release. 
PR for the NAS switch release can be found here: https://github.com/checkout/checkout-api-reference/pull/653

2022-08-08 08:08 UTC, natasha-moore-cko approved these changes

2022-08-08 15:58 UTC, natasha-moore-cko approved these changes

2022-08-09 12:22 UTC, Enrica-Mameli-cko approved these changes

2022-08-09 13:04 UTC, natasha-moore-cko approved these changes

2022-08-09 13:08 UTC, merged