[APM-3694] Add QPay Payment Request and Response source
checkout/checkout-api-reference pull request #625
Opened 2022-07-04 14:54 UTC by andrew-berestov-cko

# Description of changes in PR

Add QPay Payment Request and Response source

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-07-04 15:20 UTC, alex-larin-cko approved these changes

2022-07-15 08:21 UTC, Enrica-Mameli-cko requested changes

2022-07-15 08:21 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseQPaySource.yaml
> +    properties:
in MBC we are not returning any of these data to the merchant
why do we have to do it now?
what the merchant will do with this information?
why should be passed in the source?

2022-07-15 11:27 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseQPaySource.yaml
> +    properties:
I am discussing with Anastasiya and we can probably generalise this

can you clarify what is the confirmation_id?
is this kind of an authentication or authorization id?

2022-07-19 10:24 UTC, Enrica-Mameli-cko requested changes

2022-07-19 10:24 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseQPaySource.yaml
> +      qpay_status:
as agreed in today meeting `qpay_status ` should be returned in `processing` as `partner_status_code`

2022-07-19 10:24 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseQPaySource.yaml
> +      status_message:
as agreed in today meeting `status_message ` should be returned in `processing` as `partner_status_description`

2022-07-19 10:24 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseQPaySource.yaml
> +      confirmation_id:
as agreed in today meeting `confirmation_id` should be returned in `processing` as `partner_ confirmation_id`

2022-07-19 10:24 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseQPaySource.yaml
> +      pun:
as agreed in today meeting `pun` should be returned in `processing` as `partner_ payment_id`

2022-07-19 15:57 UTC, Enrica-Mameli-cko reviewed
please do not action the request changes until is clear if we are talking about the payment response or the get payment details response!

2022-08-03 09:22 UTC, tania-asimionesei-cko commented
Please note that on the 27th of July we had a BREAKING CHANGE release, where the ABC and NAS versions of the API reference were switched in line with company-wide NAS readiness OKR and initiative. Therefore please make sure that you address any conflicts and updates in line with the latest release. 
PR for the NAS switch release can be found here: https://github.com/checkout/checkout-api-reference/pull/653

2022-08-08 13:23 UTC, Enrica-Mameli-cko reviewed
https://github.com/checkout/checkout-api-reference/pull/625#pullrequestreview-1043695655

according to the [payload agreement](https://docs.google.com/document/d/1ia5zhpJQKSpV403txMXlyeQXnw50CUajZ59BEoraUqs/edit) all those field should be in the GET response not in the payment response and I agree we cannot move anything in the payment response as it will break merchant integration. this is an old implementation and we will do an exception

2022-08-09 12:29 UTC, andre-lopes-cko commented
Handled in this PR
https://github.com/checkout/checkout-api-reference/pull/671

2022-08-09 12:29 UTC, closed without merging