Add Sofort Request and Response source API reference
checkout/checkout-api-reference pull request #626
Opened 2022-07-05 07:08 UTC by andre-lopes-cko

# Description of changes in PR

[//]: # 'Add Sofort Request and Response API references'

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-07-05 08:01 UTC, ben-ahmady-cko approved these changes
Approving but `gateway-product-cko` also needs to approve

2022-07-05 19:45 UTC, Joshua-Bedeau-cko requested changes

2022-07-05 19:45 UTC, Joshua-Bedeau-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestSofortSource.yaml
> +      languageCode:
Hello @andre-lopes-cko should this field be in snake case rather than camel to comply with merchant API standards?
In GW3 MBC it looks like we have a different field property for language, so if we want to append code can we please update the formatting
https://checkout.atlassian.net/wiki/spaces/CoreEng/pages/180584800/Merchant-facing+API+Standards

2022-07-05 20:12 UTC, andre-lopes-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestSofortSource.yaml
> +      languageCode:
Yes.
For Sofort on NAS APM it has been the design for these two properties.
Updating now would probably break some merchant's integration.

2022-07-14 09:25 UTC, Joshua-Bedeau-cko submitted a review, later dismissed

2022-07-15 08:00 UTC, Enrica-Mameli-cko submitted a review, later dismissed

2022-07-15 13:22 UTC, Enrica-Mameli-cko approved these changes

2022-07-15 13:23 UTC, Enrica-Mameli-cko requested changes

2022-07-15 13:23 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseSofortSource.yaml
> +description: 'PayPal payment source'
'PayPal payment source'?

2022-07-15 13:24 UTC, andre-lopes-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseSofortSource.yaml
> +description: 'PayPal payment source'
OMG!
That was missed. 
Fixing in 2 seconds

2022-07-15 13:26 UTC, andre-lopes-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseSofortSource.yaml
> +description: 'PayPal payment source'
done 👍

2022-07-15 14:30 UTC, Enrica-Mameli-cko approved these changes

2022-07-18 08:43 UTC, sebastian-garcia-cardona-cko approved these changes

2022-07-18 08:44 UTC, sebastian-garcia-cardona-cko approved these changes

2022-07-18 08:48 UTC, merged