APM-5212: Klarna sources updated
checkout/checkout-api-reference pull request #630
Opened 2022-07-05 10:34 UTC by michael-zhukov-cko

# Description of changes in PR

Updated Klarna response and request sources
Jira: https://checkout.atlassian.net/browse/APM-5212

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

2022-07-13 06:59 UTC, alex-larin-cko submitted a review, later dismissed

2022-08-03 09:20 UTC, tania-asimionesei-cko commented
Please note that on the 27th of July we had a BREAKING CHANGE release, where the ABC and NAS versions of the API reference were switched in line with company-wide NAS readiness OKR and initiative. Therefore please make sure that you address any conflicts and updates in line with the latest release. 
PR for the NAS switch release can be found here: https://github.com/checkout/checkout-api-reference/pull/653

2022-08-09 09:42 UTC, Enrica-Mameli-cko requested changes

2022-08-09 09:42 UTC, Enrica-Mameli-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +        description: 'RFC 1766 customer''s locale.'
could we put here a description that express what this data represent
eg. _Used to define the language and region of the customer. RFC 1766 customer's locale._

2022-08-09 09:42 UTC, Enrica-Mameli-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +        description: 'ISO 3166 alpha-2 purchase country.'
could we put here a description that express what this data represent
eg._The purchase country of the merchant's store. ISO 3166 alpha-2 purchase country_

2022-08-09 09:42 UTC, Enrica-Mameli-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
>        auto_capture:
this does not match with the [payload agreement](https://docs.google.com/document/d/1tDyPOLHG8fE2yb-yiE1MCs9xMv_VUJrqawkFa2HDnhw/edit#)
auto capture already exist in upapi outside of the source object as capture=true for autocapture and capture=false for 2 step payment 
https://api-reference.checkout.com/#operation/requestAPaymentOrPayout
<img width="516" alt="image" src="https://user-images.githubusercontent.com/93340823/183616976-22428edc-6110-411d-b97e-2e4d03f8bba4.png">

2022-08-09 09:42 UTC, Enrica-Mameli-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
>        products:
this does not match with the [payload agreement](https://docs.google.com/document/d/1tDyPOLHG8fE2yb-yiE1MCs9xMv_VUJrqawkFa2HDnhw/edit#)
we do not use `product` in UPAPI we adopted the term `item`

2022-08-09 09:42 UTC, Enrica-Mameli-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +      custom_payment_method_ids:
this does not match with the [payload agreement](https://docs.google.com/document/d/1tDyPOLHG8fE2yb-yiE1MCs9xMv_VUJrqawkFa2HDnhw/edit#)

2022-08-09 09:42 UTC, Enrica-Mameli-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +      billing_address:
All the response does not match not match with the [payload agreement](https://docs.google.com/document/d/1tDyPOLHG8fE2yb-yiE1MCs9xMv_VUJrqawkFa2HDnhw/edit#)

2022-08-11 09:22 UTC, Enrica-Mameli-cko approved these changes

2022-08-11 10:06 UTC, natasha-moore-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'Customer''s billing address.'
```suggestion
        description: 'Customer's billing address.'
```

2022-08-11 10:06 UTC, natasha-moore-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'Customer''s shipping address.'
```suggestion
        description: 'Customer's shipping address.'
```

2022-08-11 10:08 UTC, natasha-moore-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase.'
```suggestion
        description: 'This array can be used to define which of the configured payment options within a payment category (`pay_later`, `pay_over_time`, etc.) should be shown for this purchase.'
```

2022-08-11 10:09 UTC, natasha-moore-cko commented on abc_spec/changelog.md
> +| 2022/07/05 | Update Klarna Payment Request &  Response source.                                                                    |
```suggestion
| 2022/08/11 | Update Klarna Payment Request &  Response source.  
| 2022/07/14 | Add `locale` property to Get Payment Link details response                                                      |
                                                                  |
```

2022-08-11 10:10 UTC, natasha-moore-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +        description: 'Used to define the language and region of the customer. RFC 1766 customer''s locale.'
```suggestion
        description: 'Used to define the language and region of the customer. RFC 1766 customer's locale.'
```

2022-08-11 10:11 UTC, natasha-moore-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +        description: "The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase.  \nThis o
```suggestion
        description: "This array can be used to define which of the configured payment options within a payment category (`pay_later`, `pay_over_time`, etc.) should be shown for this purchase.  \nThis object is passed directly to Klarna as `custom_payment_method_ids`, \nso for the object definition use the [Klarna documentation](https://developers.klarna.com/api/#payments-api__create-a-new-order__custom_payment_method_ids)."
```

2022-08-11 11:26 UTC, michael-zhukov-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'Customer''s billing address.'
according to yaml specification, it is valid. For single-quoted strings, any single quote ' inside its contents must be doubled to escape it
https://yaml.org/spec/1.2.2/#rule-c-quoted-quote

2022-08-11 11:26 UTC, michael-zhukov-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +        description: 'RFC 1766 customer''s locale.'
done

2022-08-11 11:26 UTC, michael-zhukov-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +        description: 'ISO 3166 alpha-2 purchase country.'
done

2022-08-11 11:26 UTC, michael-zhukov-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'Customer''s shipping address.'
as above

2022-08-11 11:28 UTC, natasha-moore-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'Customer''s billing address.'
Thanks, feel free to ignore in that case

2022-08-11 11:33 UTC, michael-zhukov-cko commented on abc_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +        description: "The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase.  \nThis o
applied

2022-08-11 11:33 UTC, michael-zhukov-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase.'
fixed

2022-08-11 11:38 UTC, michael-zhukov-cko commented on abc_spec/components/schemas/Payments/ResponseSources/PaymentResponseKlarnaSource.yaml
> +        description: 'The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase.'
fixed

2022-08-11 11:42 UTC, natasha-moore-cko approved these changes

2022-08-11 12:53 UTC, Enrica-Mameli-cko approved these changes

2022-08-11 14:11 UTC, merged