WE-1648 | NAS Switch
checkout/checkout-api-reference pull request #653
Opened 2022-07-25 14:45 UTC by adam-young-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-07-25 15:10 UTC, sebastian-garcia-cardona-cko approved these changes

2022-07-25 15:48 UTC, jason-dantzer-cko approved these changes
LGTM

2022-07-26 08:50 UTC, tania-asimionesei-cko commented on vercel.json
> +  "redirects": [
Thanks for adding the redirect

2022-07-26 08:50 UTC, tania-asimionesei-cko commented on web/index.html
> +		<script async tyoe="text/plain" src="https://www.googletagmanager.com/gtag/js?id=UA-83886670-8"></script>
tyoe="text/plain" has a typo

2022-07-26 08:53 UTC, tania-asimionesei-cko commented on web/index.html
> -		<script src="js/show-footer.js"></script>
We don't need the footer anymore?

2022-07-26 08:55 UTC, tania-asimionesei-cko requested changes
Just a couple of small things that I've spotted in the single comments. 
Everything else looks good thanks @adam-young-cko

2022-07-26 09:23 UTC, adam-young-cko commented
@tania-asimionesei-cko Scripts should be fixed, and adjusted the footer logic slightly as it was overlapping the content. All should be rendering as it should now

2022-07-26 10:45 UTC, jack-hutchinson-cko submitted a review, later dismissed
LGTM

2022-07-26 14:54 UTC, adam-young-cko commented
@tania-asimionesei-cko Footer should now be "fixed" (it still overlaps but it's at least wrapping like we mentioned)

2022-07-27 05:58 UTC, tania-asimionesei-cko requested changes
Thanks a lot @adam-young-cko . 
Just one small thing that somehow we all missed, the URL for the banner, is pointing to the main tech docs instead of the previous API ref:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/45761718/181172120-feabe6a1-3d9b-4fd6-9125-67a9cb9925ac.png">

2022-07-27 08:40 UTC, tania-asimionesei-cko approved these changes
Thanks @adam-young-cko

2022-07-27 10:00 UTC, chrisi-webster-cko approved these changes

2022-07-27 10:02 UTC, merged