GTW-7651: Split 3ds request into 3rd party and standalone
checkout/checkout-api-reference pull request #661
Opened 2022-08-03 08:54 UTC by sam-bonheure-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-08-04 10:07 UTC, jason-dantzer-cko requested changes

2022-08-04 10:07 UTC, jason-dantzer-cko commented on nas_spec/components/schemas/Payments/3dsRequestThirdParty.yaml
> +description: Required Third Party 3DS authentication information
"Required information to process a payment that has been 3DS authenticated [using a third-party provider](https://www.checkout.com/docs/payments/regulation-support/3d-secure-payments-with-a-third-party-provider#The_request)

2022-08-05 10:29 UTC, sam-bonheure-cko commented on nas_spec/components/schemas/Payments/3dsRequestThirdParty.yaml
> +description: Required Third Party 3DS authentication information
[Update descriptions](https://github.com/checkout/checkout-api-reference/pull/661/commits/4b3afe301b8b0229a549bb2e8fc9a5074f99a308)

2022-08-05 10:29 UTC, sam-bonheure-cko commented on nas_spec/components/schemas/Payments/3dsRequestStandalone.yaml
> +description: Required Standalone 3DS authentication information
[Update descriptions](https://github.com/checkout/checkout-api-reference/pull/661/commits/4b3afe301b8b0229a549bb2e8fc9a5074f99a308)

2022-08-05 13:08 UTC, Joshua-Bedeau-cko submitted a review, later dismissed

2022-08-15 09:10 UTC, sebastian-garcia-cardona-cko commented
@sam-bonheure-cko just a reminder that your branch has merge conflicts. You'll need to resolve these so reviewers can approve

2022-09-01 16:54 UTC, jason-dantzer-cko approved these changes

2022-09-02 14:00 UTC, sebastian-garcia-cardona-cko approved these changes

2022-09-05 08:37 UTC, merged