APM-3665 - Add API Reference for NAS for KNET
checkout/checkout-api-reference pull request #677
Opened 2022-08-18 12:27 UTC by joao-nadais-cko

# Description of changes in PR

Add specs for KNet in NAS (copied from ABC)

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-08-18 15:39 UTC, natasha-moore-cko requested changes

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          Note that 'ar' corresponds to 'ARA' and 'en' to 'USA' values accepted by KNet Gateway
```suggestion
          Note that 'ar' corresponds to 'ARA' and 'en' to 'USA' values accepted by KNet Gateway.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          Only alphanumeric characters and spaces are allowed
```suggestion
          Only alphanumeric characters and spaces are allowed.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          Only alphanumeric characters and spaces are allowed
```suggestion
          Only alphanumeric characters and spaces are allowed.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          exists because a card token is passed to KNet Gateway as user defined field 3
```suggestion
          exists because a card token is passed to KNet Gateway as `user_defined_field3`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          Note that this field must be omitted when the ptlf field is not empty. This restriction
```suggestion
          Note that this field must be omitted when the `ptlf` field is not empty. This restriction
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          exists because a PTLF value is passed to KNet Gateway as user defined field 5
```suggestion
          exists because a PTLF value is passed to KNet Gateway as `user_defined_field5`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          exists because a card token is passed to KNet Gateway as user defined field 3
```suggestion
          exists because a card token is passed to KNet Gateway as `user_defined_field3`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKnetSource.yaml
> +          exists because a PTLF value is passed to KNet Gateway as user defined field 5
```suggestion
          exists because a PTLF value is passed to KNet Gateway as `user_defined_field5`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          This field enables the Issuer's site to select the Consumer's preferred language
```suggestion
          This field enables the issuer's site to select the consumer's preferred language
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          (e.g. the language selected on the Merchant's site), if the Issuer's site supports this.
```suggestion
          (e.g. the language selected on the merchant's site), if the issuer's site supports this.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          User-defined field that can be used to pass and store any additional transaction data
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          User-defined field can be used to pass and store any additional transaction data
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          User-defined field can be used to pass and store any additional transaction data
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          Note that this field must be omitted when the card_token field is not empty. This restriction
```suggestion
          Note that this field must be omitted when the `card_token` field is not empty. This restriction
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          exists because a card token is passed to KNet Gateway as user defined field 3.
```suggestion
          exists because a card token is passed to KNet Gateway as `user_defined_field3`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          User-defined field can be used to pass and store any additional transaction data
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          required to be archived with the transaction and available as a searching criteria.
```suggestion
          User-defined field can be used to pass and store any additional transaction data
          required to be archived with the transaction and available as a searching criterion.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          Note that this field must be omitted when the ptlf field is not empty. This restriction
```suggestion
          Note that this field must be omitted when the `ptlf` field is not empty. This restriction
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          exists because a PTLF value is passed to KNet Gateway as user defined field 5.
```suggestion
          exists because a PTLF value is passed to KNet Gateway as `user_defined_field5`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          Note that user_defined_field3 must be omitted when the card_token field is not empty. This restriction
```suggestion
          Note that `user_defined_field3` must be omitted when the `card_token` field is not empty. This restriction
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          exists because a card token is passed to KNet Gateway as user defined field 3.
```suggestion
          exists because a card token is passed to KNet Gateway as `user_defined_field3`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          Note that user_defined_field5 must be omitted when the ptlf field is not empty. This restriction
```suggestion
          Note that `user_defined_field5` must be omitted when the `ptlf` field is not empty. This restriction
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          exists because a PTLF value is passed to KNet Gateway as user defined field 5.
```suggestion
          exists because a PTLF value is passed to KNet Gateway as `user_defined_field5`.
```

2022-08-18 15:39 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseKnetSource.yaml
> +          The state of the payment, retunrned by KNet Gateway in the response from the payment inquiry.
```suggestion
          The state of the payment, returned by KNet Gateway in the response from the payment inquiry.
```

2022-08-19 08:12 UTC, natasha-moore-cko submitted a review, later dismissed

2022-08-25 13:59 UTC, Enrica-Mameli-cko submitted a review, later dismissed

2022-08-26 08:14 UTC, natasha-moore-cko submitted a review, later dismissed

2022-08-26 13:48 UTC, Enrica-Mameli-cko approved these changes

2022-08-26 13:55 UTC, natasha-moore-cko approved these changes

2022-08-26 13:55 UTC, merged