Add P24 request and response for nas
checkout/checkout-api-reference pull request #679
Opened 2022-08-18 13:16 UTC by ahmed-ali-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-08-18 15:53 UTC, natasha-moore-cko requested changes

2022-08-18 15:53 UTC, natasha-moore-cko commented on nas_spec/changelog.md
> +| 2022/08/18 | Add p24 NAS Request and Response ource.                                                                               |
```suggestion
| 2022/08/18 | Add P24 NAS Request and Response source.                                                                               |
```

2022-08-18 15:53 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestP24Source.yaml
> +        description: 'RFC compliant email address of the account holder.'
```suggestion
        description: 'RFC-compliant email address of the account holder.'
```

2022-08-18 15:53 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/ResponseSources/PaymentResponseP24Source.yaml
> +        description: "P24 generated payment descriptor, which will contain requested billing descriptor or merchant's default descriptor  (subject to truncation)."
```suggestion
        description: "P24-generated payment descriptor, which contains the requested billing descriptor or the merchant's default descriptor (subject to truncation)."
```

2022-08-25 13:57 UTC, Enrica-Mameli-cko approved these changes

2022-08-25 14:38 UTC, natasha-moore-cko approved these changes

2022-08-25 14:39 UTC, merged