APM-4977 - add postfinance API reference on NAS
checkout/checkout-api-reference pull request #680
Opened 2022-08-18 13:19 UTC by joao-nadais-cko

# Description of changes in PR

Add postfinance API reference for NAS

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-08-18 15:47 UTC, natasha-moore-cko requested changes

2022-08-18 15:47 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestPostfinanceSource.yaml
> +description: 'P24 Source'
```suggestion
description: 'Postfinance Source'
```

2022-08-19 08:11 UTC, natasha-moore-cko approved these changes

2022-08-29 09:56 UTC, joao-nadais-cko commented
PR replaced by https://github.com/checkout/checkout-api-reference/pull/678/

2022-08-29 09:56 UTC, closed without merging