APM-4931: Request and response sources for One Klarna added
checkout/checkout-api-reference pull request #682
Opened 2022-08-18 18:38 UTC by michael-zhukov-cko

# Description of changes in PR

One Klarna Api reference added 

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-08-19 10:32 UTC, Enrica-Mameli-cko approved these changes
left some minor comment on descriptions that should be completed before merging

2022-08-19 10:32 UTC, Enrica-Mameli-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +            type: string
date_of_birth and gender do not have any description

2022-08-22 07:09 UTC, michael-zhukov-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestKlarnaSource.yaml
> +            type: string
fixed

2022-08-29 08:42 UTC, alex-larin-cko submitted a review, later dismissed

2022-08-30 09:40 UTC, Enrica-Mameli-cko approved these changes

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko requested changes

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: 'The purchase country of the customer. ISO 3166 alpha-2 purchase country'
```suggestion
    description: 'The purchase country of the customer, as an ISO 3166 alpha-2 country code.'
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: ISO 639-2 language code
```suggestion
    description: The language, as an ISO 639-2 code.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: The Klarna Order Id associated for the payment
```suggestion
    description: The Klarna order ID associated with the payment.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: The Klarna Fraud Status associated for the payment
```suggestion
    description: The Klarna fraud status associated with the payment.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: Initial/Authorized payment method.
```suggestion
    description: The initial or authorized payment method.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +        description: Payment option type name
```suggestion
        description: The payment option's type name.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +        description: Payment option description
```suggestion
        description: The payment option's description.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +        description: Payment option number of installments
```suggestion
        description: The payment option's number of installments.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +        description: Payment option number of installments
```suggestion
        description: The payment option's number of days.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +        description: Payment option number of installments
Worth adding to this description i.e. is it number of days to pay or something else?

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +      The array could be used to define which of the configured payment
```suggestion
      An array defining which of the configured payment options within a payment category (for example, `pay_later` or `pay_over_time`) should be displayed for this purchase.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +      options within a payment category (pay_later, pay_over_time, etc.)
Delete if above change is accepted.

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +      should be shown for this purchase.
As above, delete if single-line description is accepted.

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingSettings.yaml
> +    description: The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase.
```suggestion
    description: An array defining which of the configured payment options within a payment category (for example, `pay_later` or `pay_over_time`) should be displayed for this purchase.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingSettings.yaml
> +      URL which be used to notify the client that the order has been created.
```suggestion
      A URL which you can use to notify the customer that the order has been created.
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingSettings.yaml
> +    description: 'Delay before the order will be shipped.'
```suggestion
    description: 'The delay before the order will be shipped.'
```

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingSettings.yaml
> +    description: 'Delay before the order will be shipped.'
We should also add whether this integer represents calendar days, working days, etc.

2022-08-31 12:24 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/ProcessingSettings.yaml
> +    description: Shipping information for this capture. Maximum 500 items.
```suggestion
    description: The shipping information for the payment capture. Maximum 500 items.
```

2022-09-02 13:16 UTC, alex-larin-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +        description: Payment option number of installments
@sebastian-garcia-cardona-cko , yes, this is the frequency of the intervals of the payment

2022-09-06 15:22 UTC, sebastian-garcia-cardona-cko approved these changes

2022-09-06 15:27 UTC, Enrica-Mameli-cko submitted a review, later dismissed

2022-09-07 10:15 UTC, sebastian-garcia-cardona-cko approved these changes

2022-09-07 11:14 UTC, Enrica-Mameli-cko approved these changes

2022-09-07 11:54 UTC, merged