APM-5896 STC Pay API reference
checkout/checkout-api-reference pull request #685
Opened 2022-08-23 06:12 UTC by andreas-alapert-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-08-23 13:18 UTC, Enrica-Mameli-cko requested changes

2022-08-23 13:26 UTC, andreas-alapert-cko commented on nas_spec/components/schemas/Payments/CaptureRequest.yaml
> +  otp_value:
Fixed

2022-08-30 08:20 UTC, Enrica-Mameli-cko approved these changes

2022-08-30 15:22 UTC, sebastian-garcia-cardona-cko submitted a review, later dismissed

2022-08-31 09:06 UTC, Enrica-Mameli-cko approved these changes

2022-08-31 14:43 UTC, sebastian-garcia-cardona-cko approved these changes

2022-08-31 14:45 UTC, merged