Task/apm 4868 add trustly api reference
checkout/checkout-api-reference pull request #722
Opened 2022-09-26 13:36 UTC by irena-saraci-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-09-26 14:06 UTC, Enrica-Mameli-cko submitted a review, later dismissed

2022-09-26 14:20 UTC, sebastian-garcia-cardona-cko requested changes

2022-09-27 08:20 UTC, irena-saraci-cko commented on nas_spec/components/schemas/Payments/RequestSources/PaymentRequestTrustlySource.yaml
> +        description: The billing address of the cardholder
done

2022-09-27 08:33 UTC, Enrica-Mameli-cko approved these changes

2022-09-27 08:57 UTC, sebastian-garcia-cardona-cko approved these changes

2022-12-15 13:02 UTC, sebastian-garcia-cardona-cko approved these changes

2022-12-15 13:36 UTC, Enrica-Mameli-cko approved these changes

2022-12-15 14:45 UTC, merged