Add Tamara API reference
checkout/checkout-api-reference pull request #738
Opened 2022-10-07 14:59 UTC by irena-saraci-cko

# Description of changes in PR

API Reference for Tamara APM https://checkout.atlassian.net/browse/APM-4021

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-10-11 17:28 UTC, sebastian-garcia-cardona-cko requested changes

2022-10-11 17:28 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/Items.yaml
> +      description: Link to the line items product page
```suggestion
      description: Link to the line item's product page
```

2022-10-11 17:28 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/Items.yaml
> +      description: Link to the picture of the line item
```suggestion
      description: Link to the line item's product image
```

2022-10-11 17:31 UTC, sebastian-garcia-cardona-cko commented on nas_spec/changelog.md
> +| 2022/09/27 | Add Tamara NAS Request and Response source.                                                                           |
```suggestion
| 2022/10/11 | Add Tamara NAS Request and Response source.                                                                           | 
```

2022-10-12 08:06 UTC, Enrica-Mameli-cko approved these changes

2022-10-12 11:02 UTC, sebastian-garcia-cardona-cko approved these changes

2022-10-12 11:53 UTC, merged