Add prism score property to payment response risk object
checkout/checkout-api-reference pull request #762
Opened 2022-11-01 16:23 UTC by katy-hughes-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-11-01 17:42 UTC, sam-bonheure-cko commented on nas_spec/components/schemas/Payments/PaymentResponse.yaml
> +      score:
I would also add it to the Get Response since that will be done in a upcoming task

2022-11-01 17:58 UTC, jason-dantzer-cko requested changes

2022-11-01 17:58 UTC, jason-dantzer-cko commented on nas_spec/components/schemas/Payments/PaymentResponse.yaml
> +        description: The risk score calculated by Checkout. Absent if not enough data provided.
The description should be 

> The risk score calculated by our Fraud detection engine. Absent if not enough data provided.

2022-11-02 09:28 UTC, katy-hughes-cko commented on nas_spec/components/schemas/Payments/PaymentResponse.yaml
> +        description: The risk score calculated by Checkout. Absent if not enough data provided.
oops, fixed!

2022-11-02 09:28 UTC, katy-hughes-cko commented on nas_spec/components/schemas/Payments/PaymentResponse.yaml
> +      score:
👍

2022-11-02 12:08 UTC, jason-dantzer-cko submitted a review, later dismissed

2022-11-17 10:46 UTC, sam-bonheure-cko approved these changes

2022-11-17 10:47 UTC, jason-dantzer-cko submitted a review, later dismissed

2022-11-17 11:30 UTC, eoin-shaughnessy-cko commented on nas_spec/components/schemas/Payments/Payment.yaml
> +        description: The risk score calculated by our Fraud detection engine. Absent if not enough data provided.
```suggestion
        description: The risk score calculated by our Fraud Detection engine. Absent if not enough data provided.
```
Reason for change: to align with mentions of this term in https://www.checkout.com/docs/risk-management/fraud-detection :)

2022-11-17 11:30 UTC, eoin-shaughnessy-cko commented on nas_spec/components/schemas/Payments/PaymentDetails.yaml
> +        description: The risk score calculated by our Fraud detection engine. Absent if not enough data provided.
```suggestion
        description: The risk score calculated by our Fraud Detection engine. Absent if not enough data provided.
```

2022-11-17 11:30 UTC, eoin-shaughnessy-cko commented on nas_spec/components/schemas/Payments/PaymentResponse.yaml
> +        description: The risk score calculated by our Fraud detection engine. Absent if not enough data provided.
```suggestion
        description: The risk score calculated by our Fraud Detection engine. Absent if not enough data provided.
```

2022-11-17 13:54 UTC, eoin-shaughnessy-cko approved these changes

2022-11-17 14:24 UTC, sam-bonheure-cko approved these changes

2022-11-17 14:37 UTC, jason-dantzer-cko approved these changes

2022-11-17 15:51 UTC, merged