Add API key auth to Integrated Platforms balances and entity update endpoints
checkout/checkout-api-reference pull request #796
Opened 2022-12-20 08:56 UTC by chris-mannix-cko

# Description of changes in PR

Adds API key auth to the auth annotations for Balances and entity update endpoints (the former has just been added, the latter was missed in the previous update)

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [x] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-12-22 10:04 UTC, gareth-forshaw-cko requested changes
All looks good, just the one comment.

2022-12-22 10:04 UTC, gareth-forshaw-cko commented on nas_spec/changelog.md
> +| 2022/12/15 | Change Platforms schedule `by_day` response samples to use arrays                                                     |
`| 2022/12/15 | Change Platforms schedule `by_day` response samples to use arrays .`

2022-12-22 10:04 UTC, gareth-forshaw-cko commented on nas_spec/changelog.md
> +| 2022/12/15 | Change Platforms schedule `by_day` response samples to use arrays                                                     |
Minor but other lines end with "."

2022-12-22 16:21 UTC, gareth-forshaw-cko approved these changes

2023-01-04 10:21 UTC, natasha-moore-cko approved these changes

2023-01-04 10:22 UTC, merged