Add patch endpoint for payment instruments
checkout/checkout-api-reference pull request #797
Opened 2022-12-20 14:58 UTC by martyna-lachut-cko

# Description of changes in PR

[//]: # 'Please add your description here'
Added documentation for updating payment instruments (PATCH endpoint)

## Checklist

- [X ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2022-12-22 10:27 UTC, gareth-forshaw-cko requested changes
Minor comment but looks good.

2022-12-22 10:27 UTC, gareth-forshaw-cko commented on nas_spec/changelog.md
> +| 2022/12/20 | Add Platforms Update Payment Instrument Request spec                                                                            |
Minor but "." would be more consistent.

2022-12-22 10:27 UTC, gareth-forshaw-cko commented on nas_spec/paths/accounts@entities@{entityId}@payment-instruments@{id}.yaml
> +      description: Payment Instrument updated successfully
Not sure if this is hardcoded or not, but if not, ideally lower case "i", "Payment **i**nstrument"

2022-12-22 16:26 UTC, gareth-forshaw-cko submitted a review, later dismissed

2023-01-03 15:32 UTC, natasha-moore-cko requested changes

2023-01-03 15:32 UTC, natasha-moore-cko commented on nas_spec/changelog.md
> +| 2022/12/23 | Add Platforms Update Payment Instrument Request spec.                                                                 |
```suggestion
| 2023/01/03 | Add Platforms Update Payment Instrument Request spec.                                                                 |
```

2023-01-03 17:24 UTC, natasha-moore-cko approved these changes

2023-01-04 09:28 UTC, merged