Add properties for payment.processing response
checkout/checkout-api-reference pull request #820
Opened 2023-01-18 07:06 UTC by yelena-pakumirzakova-cko

# Description of changes in PR

[//]: # Added properties Payment response Processing

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

[Jira](https://checkout.atlassian.net/browse/APM-7293)

2023-01-18 15:13 UTC, Enrica-Mameli-cko reviewed
retrieval_reference_number description should be more generic to be applicable to Card processing and APM

2023-01-18 17:55 UTC, Enrica-Mameli-cko submitted a review, later dismissed
retrieval_reference_number description should be more generic to be applicable to Card processing and APM

2023-01-20 10:42 UTC, gareth-forshaw-cko requested changes
Minor query around the "P" and could we please can we add a changelog entry for this change?

2023-01-20 10:42 UTC, gareth-forshaw-cko commented on nas_spec/components/schemas/Payments/PaymentResponse.yaml
> +        description: "Unique identification of a payment provided by Partner"
Minor one but for the "Partner"'s I think we can use a lower-case "P", i.e., "partner". Unless there is a specific use case for the "P"?

2023-01-20 13:30 UTC, Enrica-Mameli-cko submitted a review, later dismissed

2023-01-24 09:47 UTC, gareth-forshaw-cko approved these changes

2023-01-24 10:06 UTC, merged