API reference for the Financial Actions API
checkout/checkout-api-reference pull request #825
Opened 2023-01-19 12:14 UTC by vasco-grilo-cko

# Description of changes in PR

[//]: # 'Added the API reference for the upcoming Financial Actions API in NAS.'

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2023-01-20 11:40 UTC, natasha-moore-cko commented
Hi @vasco-grilo-cko, is the PR ready for Tech Writer review?

2023-01-24 16:59 UTC, natasha-moore-cko requested changes

2023-01-24 16:59 UTC, natasha-moore-cko commented on nas_spec/components/schemas/FinancialActions/FinancialAction.yaml
> +    description: The timestamp of when a gateway request was made for an action expressed in ISO format in UTC.
```suggestion
    description: An ISO 8601 timestamp of when a gateway request was made for an action, in UTC.
```

2023-01-24 16:59 UTC, natasha-moore-cko commented on nas_spec/components/schemas/FinancialActions/FinancialActionBreakdown.yaml
> +    description: The associated amount of the financial action in the held currency.
```suggestion
    description: The associated amount of the financial action in the holding currency.
```

2023-01-24 16:59 UTC, natasha-moore-cko commented on nas_spec/components/schemas/FinancialActions/FinancialActionBreakdown.yaml
> +    description: The associated amount of the financial action in the processed currency.
```suggestion
    description: The associated amount of the financial action in the processing currency.
```

2023-01-24 16:59 UTC, natasha-moore-cko commented on nas_spec/components/schemas/FinancialActions/FinancialActionBreakdown.yaml
> +    description: The date that the reserve is scheduled to be released for a Rolling Reserve Deducted or the date that the reserve is released for a Rolling Reserve Released financial action.
```suggestion
    description: The date that the reserve is scheduled to be released for a Rolling Reserve Deducted, or the date that the reserve is released for a Rolling Reserve Released financial action.
```

2023-01-24 16:59 UTC, natasha-moore-cko commented on nas_spec/components/schemas/FinancialActions/FinancialActionErrorResponse.yaml
> +    description: Request Id
```suggestion
    description: Request ID
```

2023-01-24 16:59 UTC, natasha-moore-cko commented on nas_spec/components/schemas/FinancialActions/FinancialActionListResponse.yaml
> +        description: The self object.
```suggestion
        description: The `self` object.
```

2023-01-24 16:59 UTC, natasha-moore-cko commented on nas_spec/components/securitySchemes/OAuth.yaml
> +      financial-actions: Access to all FinancialActions resources
```suggestion
      financial-actions: Access to all Financial actions resources
```

2023-01-24 17:15 UTC, natasha-moore-cko requested changes

2023-01-24 17:15 UTC, natasha-moore-cko commented on nas_spec/components/schemas/FinancialActions/FinancialAction.yaml
> +    description: The timestamp of when the action was processed and had impacted your balances in ISO format in UTC.
```suggestion
    description: An ISO 8601 timestamp of when the action was processed and impacted your balances, in UTC.
```

2023-01-24 17:32 UTC, natasha-moore-cko commented on nas_spec/paths/financial-actions.yaml
> +    Returns the list of financial actions and their details.
```suggestion
  description: |
    <span style="font-size: 14px; font-weight: 500; color: rgb(60, 4, 133); background-color: rgb(237, 222, 255); border-radius: 4px; padding: 2px 6px" >Beta</span><p></p>
    Returns the list of financial actions and their details.
```

Adds the Beta label

2023-01-24 17:51 UTC, vasco-grilo-cko commented on nas_spec/components/schemas/FinancialActions/FinancialActionListResponse.yaml
> +          href: https://api.checkout.com/financial-actions?action_id=act_wsnyzbzmr2huxcekoj7qqhxwuy&payment_id=pay_bpo6m22pnb3epe67i3l6ugtxra&limit=5
thanks for spotting, done [0c82f](https://github.com/checkout/checkout-api-reference/pull/825/commits/0c82fbfbdc71bd55b7f748b518ddedde01fb278f)

2023-01-25 09:01 UTC, natasha-moore-cko commented on nas_spec/paths/financial-actions.yaml
> +      description: Financial actions retrieved succesfully
```suggestion
      description: Financial actions retrieved successfully
```

2023-01-25 09:47 UTC, vasco-grilo-cko commented on nas_spec/paths/financial-actions.yaml
> +        default: 10
Yes, good spot @natasha-moore-cko. Done

2023-01-25 10:30 UTC, natasha-moore-cko submitted a review, later dismissed

2023-02-01 09:11 UTC, sebastian-garcia-cardona-cko approved these changes

2023-02-01 09:25 UTC, merged