Update files flows for Platforms
checkout/checkout-api-reference pull request #833
Opened 2023-01-30 17:21 UTC by martyna-lachut-cko

# Description of changes in PR

[//]: # 'Update file upload flow and added files retrieval documentation for Platforms'

## Checklist

- [X] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [X] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko requested changes

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The id of the file
```suggestion
    description: The ID of the file
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: Reasons for Invalid status. Null, if status is other than Invalid
```suggestion
    description: If `status` is `Invalid`, returns the reasons the file was invalid. If `status` is any other value, returns `Null`.
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The size of the document in KB
```suggestion
    description: The size of the file, in KB
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The ISO 8601 UTC datetime when the file was uploaded
```suggestion
    description: The date and time the file was uploaded, in ISO 8601 UTC format
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The purpose of this document
```suggestion
    description: The purpose of the file
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The purpose of this document
Is this a value that the user would have supplied themselves in the request?

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The MIME type of the document
What 
```suggestion
    description: The MIME type of the file
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileUpload.yaml
> +    description: The id of the entity this request relates to
```suggestion
    description: The ID of the entity that the request relates to
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileUploadResponse.yaml
> +    description: The maxiumum allowed file size in bytes
```suggestion
    description: The maximum file size allowed, in bytes
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileUploadResponse.yaml
> +    description: The allowed file mime types for the document purpose provided on the initial file upload request
```suggestion
    description: The MIME file types allowed for the document purpose, provided on the initial file upload request
```

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileUploadResponse.yaml
> +        description: The file upload link to send the file to, in a data-binary type request
Would replacing the first half of the sentence with the below still be accurate?

> The URL to upload the file to

Also, could you clarify what you mean by 'in a data-binary type request' please?

2023-01-31 15:58 UTC, sebastian-garcia-cardona-cko commented on nas_spec/paths/platforms-files@{file_id}.yaml
> +      description: The file identifier. It is always prefixed by `file_`.
```suggestion
      description: The ID of the file. The value is always prefixed by `file_`.
```

2023-01-31 16:30 UTC, martyna-lachut-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The purpose of this document
Yes exactly, they will have provided this value on the initial upload request.

2023-02-01 11:22 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileUploadResponse.yaml
> +        description: The file upload link to send the file to, in a data-binary type request
```suggestion
        description: The URL to upload the file to, in a data-binary type request
```

2023-02-01 11:22 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileUploadResponse.yaml
> +        description: The file upload link to send the file to, in a data-binary type request
I see, will keep that copy as-is then. Have suggested a change for the first part of the sentence

2023-02-01 11:23 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    description: The purpose of this document
Thanks, have updated the suggestion

2023-02-01 15:52 UTC, sebastian-garcia-cardona-cko approved these changes

2023-02-01 15:54 UTC, merged

2023-02-08 14:21 UTC, Armando-Ibarra commented
@martyna-lachut-cko any particular reason why this endpoint 
https://www.checkout.com/docs/platforms/onboarding/api/full/upload-a-file#Attach_the_file

Isn't on the API reference? Since this is an important step, it's odd that we do not expose the `PUT` operation.

2023-02-08 14:50 UTC, martyna-lachut-cko commented
> @martyna-lachut-cko any particular reason why this endpoint https://www.checkout.com/docs/platforms/onboarding/api/full/upload-a-file#Attach_the_file
> 
> Isn't on the API reference? Since this is an important step, it's odd that we do not expose the `PUT` operation.

Hi Armando, the PUT request doesn't pass through the Files API, it goes straight to S3, therefore I didn't include it in the API reference. What do you think @sebastian-garcia-cardona-cko  ?

2023-02-08 14:59 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    example: verified
Hey @martyna-lachut-cko, I'm just seeing this PR now as I was off last week. Should we change the `status` value in this example from `verified` to `invalid` (due to `status_reasons` being `InvalidMimeType`)?

![image](https://user-images.githubusercontent.com/88327036/217565429-89667db5-568a-40e1-8d82-d64734e803e7.png)

2023-02-08 15:07 UTC, natasha-moore-cko commented on nas_spec/components/schemas/Platforms/PlatformsFileRetrieveResponse.yaml
> +    example: verified
A couple more questions:
Should we change the `file_name` value in this example to `file.pdf` to match the mime type?
Should we add `file_name` to response examples in the docs [here](https://www.checkout.com/docs/platforms/onboarding/api/full/upload-a-file#Response_examples)?

2023-02-08 21:48 UTC, Armando-Ibarra commented
> > @martyna-lachut-cko any particular reason why this endpoint https://www.checkout.com/docs/platforms/onboarding/api/full/upload-a-file#Attach_the_file
> > Isn't on the API reference? Since this is an important step, it's odd that we do not expose the `PUT` operation.
> 
> Hi Armando, the PUT request doesn't pass through the Files API, it goes straight to S3, therefore I didn't include it in the API reference. What do you think @sebastian-garcia-cardona-cko ?

Thanks @martyna-lachut-cko, but seems that either way is passing through `files` API, because you have this PUT
`curl --location --request PUT “https://files.sandbox.checkout.com/files/ent_e5fxiiuec7yasswclx27zbpbcc/file_bbmcujt2fxmyh5pmeuz2bvvxd?AWSAccessKeyId=XX&Expires=1673456742&Signature=fg9Eq3mQBXrlnbeWCTyrURlBxQ%3X”
--data-binary '@/C:/Users/Test/test.pdf'`

And you need to call first `files.sandbox.checkout.com` even if internally this redirects to AWS

Also, this is not code friendly, consider that most of the merchants uses SDK or his own implementation for calling API's, which means that a http call must be created in order to accomplish this, this increases the complexity in code just to upload a single file.

2023-02-09 17:19 UTC, martyna-lachut-cko commented
> > > @martyna-lachut-cko any particular reason why this endpoint https://www.checkout.com/docs/platforms/onboarding/api/full/upload-a-file#Attach_the_file
> > > Isn't on the API reference? Since this is an important step, it's odd that we do not expose the `PUT` operation.
> > 
> > 
> > Hi Armando, the PUT request doesn't pass through the Files API, it goes straight to S3, therefore I didn't include it in the API reference. What do you think @sebastian-garcia-cardona-cko ?
> 
> Thanks @martyna-lachut-cko, but seems that either way is passing through `files` API, because you have this PUT `curl --location --request PUT “https://files.sandbox.checkout.com/files/ent_e5fxiiuec7yasswclx27zbpbcc/file_bbmcujt2fxmyh5pmeuz2bvvxd?AWSAccessKeyId=XX&Expires=1673456742&Signature=fg9Eq3mQBXrlnbeWCTyrURlBxQ%3X” --data-binary '@/C:/Users/Test/test.pdf'`
> 
> And you need to call first `files.sandbox.checkout.com` even if internally this redirects to AWS
> 
> Also, this is not code friendly, consider that most of the merchants uses SDK or his own implementation for calling API's, which means that a http call must be created in order to accomplish this, this increases the complexity in code just to upload a single file.

Apologies, the upload link in the public docs and here is incorrect (it's being corrected), it should be: `https://s3.eu-west-1.amazonaws.com/mp-files-api-staging-sbox/ent_e5fxiiuec7yasswclx27zbpbcc/file_bbmcujt2fxmyh5pmeuz2bvvxd?AWSAccessKeyId=XX&Expires=1673456742&Signature=fg9Eq3mQBXrlnbeWCTyrURlBxQ%3X`.
Hopefully now it is clearer to see that the request goes directly to S3.