Adding new fields to get payment's processing data
checkout/checkout-api-reference pull request #851
Opened 2023-02-13 17:59 UTC by amol-kashetwar-cko

# Description of changes in PR

Adding new fields to get payment's processing data

- processing.merchant_category_code
- processing.scheme_merchant_id
- processing.aft

## Checklist

- [X] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [X] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2023-02-14 12:29 UTC, jason-dantzer-cko requested changes

2023-02-14 12:29 UTC, jason-dantzer-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: The acceptor scheme merchant that was passed to the scheme
I would change the description to: 

> The merchant identifier that was configured with the scheme and used for the payment

2023-02-14 12:30 UTC, amol-kashetwar-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: The acceptor scheme merchant that was passed to the scheme
Made the suggested change

2023-02-14 14:10 UTC, jason-dantzer-cko approved these changes

2023-02-14 16:41 UTC, gareth-forshaw-cko requested changes

2023-02-14 16:54 UTC, gareth-forshaw-cko approved these changes

2023-02-14 16:55 UTC, amol-kashetwar-cko commented on nas_spec/components/schemas/Payments/ProcessingData.yaml
> +    description: Indicates whether the payment is an [Account Funding Transaction](https://www.checkout.com/docs/previous/payments/manage-payments/account-funding-transactions)
Done.

2023-02-16 09:31 UTC, jason-dantzer-cko approved these changes

2023-02-16 12:38 UTC, gareth-forshaw-cko approved these changes

2023-02-16 12:39 UTC, merged