GTW-9660: Add authentication_status_reason field to 3ds object
checkout/checkout-api-reference pull request #906
Opened 2023-04-13 16:01 UTC by katy-hughes-cko

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [x] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

2023-04-13 16:48 UTC, jason-dantzer-cko requested changes

2023-04-13 16:48 UTC, jason-dantzer-cko commented on nas_spec/components/schemas/Payments/3dsData.yaml
> +      Only available as a result of a 3DS2 authentication. The response from the DS or ACS which provides information on why the `authentication_response` field has the specified value. Only availabl
Can we add a line return after the sentence "...is not Y."?

2023-04-13 17:02 UTC, jason-dantzer-cko approved these changes

2023-04-14 09:32 UTC, sebastian-garcia-cardona-cko requested changes

2023-04-14 09:32 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/3dsData.yaml
> +    description: >
```suggestion
    description: |
```

2023-04-14 09:32 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/3dsData.yaml
> +      Only available as a result of a 3DS2 authentication. The response from the DS or ACS which provides information on why the `authentication_response` field has the specified value. Only availabl
```suggestion
      The response from the DS or ACS, which provides information on why you received the given `authentication_response` value. 
      
      This field is only returned as a result of a 3DS2 authentication, and only if the returned `authentication_response` value was not `Y`.
```

2023-04-14 09:32 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/3dsData.yaml
> +      <a href="https://www.checkout.com/docs/risk-management/3d-secure/sessions/understand-authentication-failures#Common_authentication_failures" target="_blank">See this page</a> for possible value
```suggestion
      Refer to our <a href="https://www.checkout.com/docs/risk-management/3d-secure/sessions/understand-authentication-failures#Common_authentication_failures" target="_blank">authentication failures</a> documentation for more information.
```

2023-04-14 09:32 UTC, sebastian-garcia-cardona-cko commented on nas_spec/components/schemas/Payments/3dsData.yaml
> +      Only available as a result of a 3DS2 authentication. The response from the DS or ACS which provides information on why the `authentication_response` field has the specified value. Only availabl
Could you also write out what DS stands for here please, followed by the acronym in brackets. Same for ACS too. E.g.

> Strong Customer Authentication (SCA)

2023-04-14 10:31 UTC, jason-dantzer-cko approved these changes

2023-04-14 13:30 UTC, sebastian-garcia-cardona-cko approved these changes

2023-04-19 08:16 UTC, merged